version: '3.9'

services:
  geomart-backend:
    build: ./server
    container_name: geomart-backend
    restart: unless-stopped
    ports:
      - "3000:4000"
    env_file:
      - ./server/.env
    networks:
      - geomart-network

  frontend:
    build: ./client
    container_name: geomart-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    env_file:
      - ./client/.env
    depends_on:
      - geomart-backend
    networks:
      - geomart-network

networks:
  geomart-network:
