apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: e-commerce-platform
type: Opaque
stringData:
  JWT_SECRET: secret#text
  SELLER_PASSWORD: Vishal@2003
  MONGODB_URI: mongodb+srv://Vishal_761:54623789@cluster0.1tqpnb2.mongodb.net/GreenCart
  CLOUDINARY_API_KEY: "113461489922123"
  CLOUDINARY_API_SECRET: Z84lbyZbMAurn2_e0XC2mMGamlk
  STRIPE_SECRET_KEY: sk_test_51S6PTk2NyX9tyPAnuuRHjheMcgzkWIVubBI2aLtkEq10tgcCFZynMpUWb0Mdw4UJlEIai82doVwvhAXSvQEIjN0Q00lbxhb6rrI
  STRIPE_WEBHOOK_SECRET: ""
