apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: e-commerce-platform
type: Opaque
stringData:
  JWT_SECRET: "<your-jwt-secret>"
  MONGODB_URI: "<your-mongodb-uri>"
  CLOUDINARY_API_KEY: "<your-key>"
  CLOUDINARY_API_SECRET: "<your-secret>"
  STRIPE_SECRET_KEY: "<your-stripe-key>"


# apiVersion: v1
# kind: Secret
# metadata:
#   name: backend-secret
#   namespace: e-commerce-platform
# type: Opaque
# stringData:
#   JWT_SECRET: c2VjcmV0I3RleHQ=
#   SELLER_PASSWORD: VmlzaGFsQDIwMDM=
#   MONGODB_URI: bW9uZ29kYitzcnY6Ly9WaXNoYWxfNzYxOjU0NjIzNzg5QGNsdXN0ZXIwLjF0cXBuYjIubW9uZ29kYi5uZXQvR3JlZW5DYXJ0
#   CLOUDINARY_API_KEY: MTEzNDYxNDg5OTIyMTIz
#   CLOUDINARY_API_SECRET: Wjg0bGJ5WmJNQXVybjJfZTBYQzJtTUdhbWxr
#   STRIPE_SECRET_KEY: c2tfdGVzdF81MVM2UFRrMk55WDl0eVBBbnV1UkhqaGVNY2d6a1dJVnViQkkyYUx0a0VxMTB0Z2NDRlp5bk1wVVdiME1kdzRVSmxFSWFpODJkb1Z3dmhBWFN2UUVJak4wUTAwbGJ4eGI2cnI=
#   STRIPE_WEBHOOK_SECRET: ""
