apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: e-commerce-platform
type: Opaque
stringData:
  MONGO_URI: "<YOUR_MONGODB_ATLAS_URI>"
  JWT_SECRET: "<YOUR_JWT_SECRET>"
  CLOUDINARY_CLOUD_NAME: "<YOUR_CLOUDINARY_CLOUD_NAME>"
  CLOUDINARY_API_KEY: "<YOUR_CLOUDINARY_API_KEY>"
  CLOUDINARY_API_SECRET: "<YOUR_CLOUDINARY_API_SECRET>"
  SELLER_PASSWORD: <"YOUR_SELLER_PASSWORD">
  STRIPE_SECRET_KEY: <"YOUR_STRIPE_SECRET_KEY">
  STRIPE_WEBHOOK_SECRET: ""